name: CustomJoinLeaveMessages
version: '1.1'
main: me.konodachi.customJoinLeaveMessages.CustomJoinLeaveMessages
api-version: '1.21'

commands:
  reloadConfig:
    description: Reloads the config for Custom Join Leave Messages plugin

permissions:
  customjoinleave.default:
    description: A permission that everyone has by default
    default: true
  customjoinleave.reloadConfig:
    description: Allows one to call the /reloadconfig command
    default: op
  customjoinleave.vip:
    description: Permission for VIP users.
    default: false
  customjoinleave.admin:
    description: Permission for mods/admins
    default: op