name: CustomJoinLeaveMessages
version: '1.0'
main: me.konodachi.customJoinLeaveMessages.CustomJoinLeaveMessages
api-version: '1.21'

permissions:
  customjoinleave.default:
    description: A permission that everyone has by default
    default: true